[package]
name = "forge-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bevy = { version = "0.13", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_asset",
    "bevy_gizmos",
    "bevy_ui",
    "bevy_text",
    "tonemapping_luts",
    "multi-threaded",
] }
futures-lite = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
forge-protocol = { path = "../protocol" }
forge-exts-slicer-prusa = { path = "../exts/slicer-prusa" }
stl_io = "0.7"
